INITIAL_SYMBOL = 'TSM'
DEFAULT_HOST = '127.0.0.1'
DEFAULT_CLIENT_ID = 1
LIVE_TRADING = True
LIVE_TRADING_PORT = 7496
PAPER_TRADING_PORT = 7497
if LIVE_TRADING:
    TRADING_PORT = LIVE_TRADING_PORT
else:
    TRADING_PORT = PAPER_TRADING_PORT

SHARE_PRICE_UNSET = -1.0